services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    networks:
      - lotto-net
    environment:
      POSTGRES_DB: ${DB_NAME:-lotto_db}
      POSTGRES_USER: ${DB_USERNAME:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    networks:
      - lotto-net
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "8086:80"
    depends_on:
      - postgres

  lotto-backend:
    image: ghcr.io/pkasiewicz/lotto-backend:latest
    container_name: lotto-backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST:-postgres}:${DB_PORT:-5432}/${DB_NAME:-lotto_db}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-admin}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-admin}
    networks:
      - lotto-net

  lotto-frontend:
    image: ghcr.io/pkasiewicz/lotto-frontend:latest
    container_name: lotto-frontend
    restart: always
    depends_on:
      - lotto-backend
    ports:
      - "8085:80"
    networks:
      - lotto-net

volumes:
  pg_data:

networks:
  lotto-net:
    external: true