spring:
  application:
    name: LottoGame
  datasource:
    url: jdbc:postgresql://localhost:5432/lotto_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
  task:
    scheduling:
      enabled: true

lotto:
  number-generator:
    count: 6
    lowerBand: 1
    upperBand: 99
    api:
      url: https://www.randomnumberapi.com/api/v1.0/random
    scheduler:
      cron: 0 0 12 ? * SAT
  number-receiver:
    count: 6
    lower-band: 1
    upper-band: 99
  result-checker:
    scheduler:
      cron: 0 5 12 ? * SAT


server:
  port: 8080