spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
    locations: classpath:db/migration
  main:
    allow-bean-definition-overriding: true
  task:
    scheduling:
      enabled: true