spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
    locations: classpath:db/migration
  main:
    allow-bean-definition-overriding: true
  task:
    scheduling:
      enabled: true

lotto:
  number-generator:
    scheduler:
      cron: "*/5 * * * * *"
  result-checker:
    scheduler:
      cron: "*/7 * * * * *"
